In [64]:
import os
import time
import copy
import torch
import pandas as pd
import numpy as np
from tqdm import tqdm
import torch.nn as nn
import torch.nn.functional as F
from torch.autograd import Variable

import argparse
from collections import defaultdict, Counter
import random

import pandas as pd
from tqdm import tqdm

In [65]:
old_data = pd.read_csv("../input/2015_data/trainLabels.csv")
old_data.columns=["id_code","diagnosis"]

In [66]:
new_data = pd.read_csv("../input/train.csv")

In [67]:
def make_folds(df, n_folds=5):
    df['diagnosis']=df['diagnosis'].astype("str")
    cls_counts = Counter(cls for classes in df['diagnosis'].str.split()
                         for cls in classes)
    fold_cls_counts = defaultdict(int)
    folds = [-1] * len(df)
    for item in tqdm(df.sample(frac=1, random_state=42).itertuples(),
                          total=len(df)):
        cls = min(item.diagnosis.split(), key=lambda cls: cls_counts[cls])
        fold_counts = [(f, fold_cls_counts[f, cls]) for f in range(n_folds)]
        min_count = min([count for _, count in fold_counts])
        random.seed(item.Index)
        fold = random.choice([f for f, count in fold_counts
                              if count == min_count])
        folds[item.Index] = fold
        for cls in item.diagnosis.split():
            fold_cls_counts[fold, cls] += 1
    df['fold'] = folds
    return df

In [68]:
df_old = make_folds(pd.concat([old_data]), n_folds=10)

100%|██████████| 35126/35126 [00:00<00:00, 73482.18it/s]

In [69]:
old_data.shape

(35126, 2)

In [70]:
df_old = df_old[df_old.fold==1].reset_index(drop=True)[["id_code","diagnosis"]]

In [75]:
df_final = pd.concat([new_data,df_old]).reset_index(drop=True)

In [76]:
df = make_folds(df_final, n_folds=5)

100%|██████████| 7174/7174 [00:00<00:00, 84321.68it/s]

In [77]:
df.to_csv("../input/new_folds.csv",index=False)

In [78]:
df

           id_code diagnosis  fold
0     000c1434d8d7         2     4
1     001639a390f0         4     0
2     0024cdab0c1e         1     2
3     002c21358ce6         0     2
4     005b95c28852         0     1
5     0083ee8054ee         4     4
6     0097f532ac9f         0     4
7     00a8624548a9         2     3
8     00b74780d31d         2     0
9     00cb6555d108         1     4
10    00cc2b75cddd         0     0
11    00e4ddff966a         2     3
12    00f6c1be5a33         0     3
13    0104b032c141         3     3
14    0124dffecf29         1     0
15    0125fbd2e791         0     1
16    012a242ac6ff         2     2
17    014508ccb9cb         0     4
18    0151781fe50b         0     2
19    0161338f53cc         2     3
20    0180bfa26c0b         2     3
21    0182152c50de         0     1
22    01b3aed3ed4c         1     0
23    01c7808d901d         2     3
24    01d9477b1171         0     0
25    01eb826f6467         2     4
26    01f7bb8be950         0     1
27    0212dd31f623         0     3
28    022f820027b8         0     0
29    0231642cf1c2         0     3
...            ...       ...   ...
7144    43903_left         2     0
7145    43904_left         0     2
7146   43912_right         0     0
7147   43933_right         0     3
7148    43945_left         0     2
7149    43966_left         0     0
7150    43995_left         0     1
7151    44005_left         0     2
7152   44007_right         0     3
7153   44014_right         0     3
7154   44027_right         0     3
7155    44032_left         0     2
7156    44053_left         0     0
7157    44076_left         0     2
7158   44079_right         0     3
7159    44084_left         0     2
7160    44086_left         0     2
7161   44086_right         0     4
7162   44093_right         2     0
7163   44099_right         0     0
7164    44146_left         2     4
7165   44193_right         2     2
7166    44205_left         0     0
7167    44217_left         0     1
7168   44229_right         0     3
7169    44275_left         1     3
7170    44278_left         0     1
7171   44306_right         0     4
7172    44325_left         0     0
7173   44331_right         0     4

[7174 rows x 3 columns]